build:
	docker build -t kubernetes-tutorial:1 .

tag:
	docker tag kubernetes-tutorial:1 190103567417.dkr.ecr.us-east-1.amazonaws.com/kubernetes-tutorial:1

run:
	docker run -d -p 3000:3000 kubernetes-tutorial:1
